# Global settings for all models
global:
  seed: 42
  replicates: 5
  num_workers: 8  # Will be set to min(8, os.cpu_count() or 1)
  epochs: 300
  patience: 30

# Dataset-specific descriptors
dataset_descriptors:
  htpmd:
    - Molality
    - Monomer_Molecular_Weight
    - DoP
    - Density

dataset_ignore:
  htpmd:
    ["Monomer_length_x","MW_ratio_x","MW",
    "Mass_max_x","Mass_ave_x","Mass_min",
    "Charge_max","Charge_min","Charge_ave",
    "Epsilon_max","Epsilon_min","Epsilon_ave",
    "Sigma_max","Sigma_min","Sigma_ave",
    "K_bond_min_x","K_bond_ave_x","K_bond_max",
    "R0_max","R0_min","R0_ave",
    "K_ang_ave_x","K_ang_max","K_ang_min",
    "Theta0_min_x","Theta0_max","Theta0_ave",
    "K_dih_max","K_dih_min","K_dih_ave",
    "ABC"]
  block:
    ["BigSMILES"]
  combined_homopolymer:
    ["dataset_source"]

# Model-specific settings
models:
  DMPNN:
    smiles_column: smiles
    ignore_columns: [WDMPNN_Input]
  
  DMPNN_DiffPool:
    smiles_column: smiles
    ignore_columns: [WDMPNN_Input]
    
  wDMPNN:
    smiles_column: WDMPNN_Input
    ignore_columns: [smiles]
    
  PPG:
    smiles_column: smiles
    ignore_columns: []

  AttentiveFP:
    smiles_column: smiles
    ignore_columns: [WDMPNN_Input]
  
  Graphormer:
    smiles_column: smiles
    ignore_columns: [WDMPNN_Input]

# Paths
paths:
  data_dir: data
  checkpoint_dir: checkpoints
  results_dir: results
  feat_select_dir: out
